name: Automerge Dependabot PRs

on:
  schedule:
    - cron: "30 4 * * 1-5"
  workflow_dispatch:
permissions: {}
concurrency:
  group: automerge-dependabot-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  automerge:
    name: Automerge
    uses: navikt/crm-workflows-base/.github/workflows/automergeDependabot.yml@main
    with:
      PLATFORM_TOKEN_APP_ID: ${{ vars.PLATFORM_TOKEN_APP_ID }}
    secrets:
      PLATFORM_TOKEN_APP_PRIVATE_KEY: ${{ secrets.PLATFORM_TOKEN_APP_PRIVATE_KEY }}
