# Unique name for this workflow
name: "Update Workflows"

# Definition when the workflow should run
on:
  schedule:
    - cron: "44,45,46,47,48,49,50 * * * *"

# Jobs to be executed
jobs:
  update:
    name: Update Workflows
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: "Checkout source code"
        uses: actions/checkout@v2
        with:
          ref: "master"

      # Clone Workflows repo
      - name: "Clone Workflows repo"
        run: |
          git clone https://github.com/navikt/crm-workflows-base.git tmp

      # Move files to correct folder
      - name: "Move files to correct folder"
        run: |
          mv tmp/workflows/* .github/workflows/

      # Delete Workflows repo
      - name: "Delete Workflows repo"
        run: |
          rm -rf tmp

      # Commit changed permsets
      - name: "Commit changed permsets"
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Updated Workflows
          branch: "master"
