name: "Generate Relese Definition"
on:
    workflow_dispatch:
        inputs:
            # gitRef:
            #     description: "Utilize the tags on the source branch to generate release definiton"
            #     required: true
            # pathToConfigFile:
            #     description: "Path to release config file"
            #     required: true
            releaseName:
                description: "Name of the release"
                required: true
                type: string
            directory:
                description: "Relative path to directory to which the release defintion file should be generated"
                required: false
                default: "./release-definitions"
jobs:
    generateReleaseDef:
        name: Generate Release Definition
        uses: navikt/crm-workflows-base/.github/workflows/cdGenerateReleaseDefinition.yml
        permissions:
            contents: write
        secrets: inherit
        with:
            gitRef: ${{ github.ref_name }}
            pathToConfigFile: "config/releaseConfig"
            releaseName: ${{ inputs.releaseName }}
            directory: ${{ inputs.directory }}