name: "[PUSH] Create artifact"
on:
    push:
        paths:
            - 'force-app/**'
            - 'unpackaged/**'
            - 'data-package/**'
            - 'sfdx-project.json'
    workflow_dispatch:
jobs:
    quickbuild:
        name: Create artifact
        uses: navikt/crm-workflows-base/.github/workflows/ciPipeline.yml@dxAtScale
        permissions:
            contents: write
            packages: write
        secrets: inherit