name: "Release version to org"
on:
    workflow_dispatch:
        inputs:
            releaseDefinitionFile:
                description: The name of the release definition file
                required: true
                type: string
            pathToReleaseDef:
                description: "Path to release definition file"
                required: true
                type: string
                default: "./release-definitions"
            org:
                description: "Org (prod, preprod, dev, uat, sit)"
                required: true
                type: string
jobs:
    cdReleaseToOrg:
        name: "Release to org"
        uses: navikt/crm-workflows-base/.github/workflows/cdReleaseToOrg.yml@dxAtScale
        permissions:
            contents: write
            packages: read
        secrets: inherit
        with:
            pathToReleaseDef: ${{ inputs.pathToReleaseDef }}/${{inputs.releaseDefinitionFile}}.yml
            org: ${{ inputs.org }}