name: "[PUSH] Synch Branches"
on:
  workflow_dispatch:
  push:
    branches:
      - new-workflows
jobs:
  # ################################################################# #
  # ######################## SYNCH BRANCHES ######################### #
  # ################################################################# #
  create-package:
    name: Synchronize branches
    runs-on: ubuntu-latest
    steps:
      # Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v2

       # Init
      - name: Init git
        run: |
          git fetch origin
          git config --local user.email "branchsyncher@github.com"
          git config --local user.name "BRANCH SYNCHER"

      # Synchronize DEV branch
      #Adding empty commit with skip ci message to override CI on push to branches.
      - name: Synchronize DEV branch
        run: |  
          {
            git switch DEV
            git merge origin/DEV
          } ||
          {
            git checkout -b DEV
          }
          git merge master
          git push origin DEV
          
          
      
      # Synchronize UAT branch
      #Adding empty commit with skip ci message to override CI on push to branches
      - name: Synchronize UAT branch
        run: |
          {
            git switch UAT
            git merge origin/UAT
          } ||
          {
            git switch -c UAT
          }
          git merge origin/master
          git push origin UAT
