name: "[PUSH] Create artifact (dxScaleQuickBuild)"
on:
    push:
    workflow_dispatch:
jobs:
    quickbuild:
        name: Create artifact
        uses: navikt/crm-workflows-base/.github/workflows/ciValidate.yml@pmd-annotation
        permissions:
            contents: write
            packages: write
        secrets: inherit
    dummy:
        name: Do nothing
        runs-on: ubuntu-latest
        needs: quickbuild
        steps:
            - name: Dummier
              run: echo Dummy run successfully.
