name: Sync Workflows

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

concurrency:
  group: sync-workflows-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:  

  sync-workflows:
    name: Sync Workflow Files
    uses: navikt/crm-workflows-base/.github/workflows/workflow-sync.yml@21bcdeeecaa439af0921db62135535c2afffe25a
    permissions:
      contents: write # Required for creating and pushing commits in the reusable workflow
      pull-requests: write # Required for creating pull requests in the reusable workflow
    secrets:
      PLATFORM_TOKEN_APP_ID: ${{ vars.PLATFORM_TOKEN_APP_ID }}
      PLATFORM_TOKEN_APP_PRIVATE_KEY: ${{ secrets.PLATFORM_TOKEN_APP_PRIVATE_KEY }}
